version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000