version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on: # new
      - web-db

  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres